export { DeskProvider, useDesk, useDeskState } from './context.js'
export type { DeskProviderProps } from './context.js'
export { Desktop } from './Desktop.js'
export type { DesktopProps } from './Desktop.js'
export { Dock, dockItem, dockSeparator, dockStack } from './Dock.js'
export type { DockEntry, DockItem, DockProps, DockStack } from './Dock.js'
